# Generated by Django 4.1 on 2022-09-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoiceVersa', '0008_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='processed',
        ),
    ]
