# Generated by Django 4.1 on 2022-09-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoiceVersa', '0009_remove_audio_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
