# Generated by Django 4.1 on 2022-09-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoiceVersa', '0010_audio_is_processed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voice',
            old_name='audio',
            new_name='url',
        ),
    ]
